# Data
data_path: "data/tiny-imagenet"
train_split: 0.7
val_split: 0.00
test_split: 0.30

# Training
learning_rate: 0.0005
weight_decay: 0.01
batch_size: 128
num_epochs: 10

# Output
save_path: "trained_models/test_model.pt"

# Testing: setting to True will use 1% of the data for quick run-through.
for_testing: False
